-- MySQL Script generated by MySQL Workbench
-- среда, 01. јул 2020. 18:22:57 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `brojIndeksa` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `pol` CHAR NULL,
  `adresa` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `jmbg` VARCHAR(13) NULL,
  PRIMARY KEY (`brojIndeksa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ustanova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ustanova` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ustanova` (
  `oznaka` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  PRIMARY KEY (`oznaka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NivoStudija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NivoStudija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NivoStudija` (
  `oznaka` VARCHAR(40) NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `Ustanova_oznaka` INT NOT NULL,
  PRIMARY KEY (`oznaka`, `Ustanova_oznaka`),
  INDEX `fk_NivoStudija_Ustanova1_idx` (`Ustanova_oznaka` ASC),
  CONSTRAINT `fk_NivoStudija_Ustanova1`
    FOREIGN KEY (`Ustanova_oznaka`)
    REFERENCES `mydb`.`Ustanova` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NastavniPredmet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NastavniPredmet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NastavniPredmet` (
  `oznaka` VARCHAR(45) NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `espb` VARCHAR(45) NULL,
  `Ustanova_oznaka` INT NOT NULL,
  PRIMARY KEY (`oznaka`, `Ustanova_oznaka`),
  INDEX `fk_NastavniPredmet_Ustanova_idx` (`Ustanova_oznaka` ASC),
  CONSTRAINT `fk_NastavniPredmet_Ustanova`
    FOREIGN KEY (`Ustanova_oznaka`)
    REFERENCES `mydb`.`Ustanova` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentskiProgram`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentskiProgram` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentskiProgram` (
  `oznaka` VARCHAR(45) NOT NULL,
  `nivo` INT NULL,
  `StudentskiProgramcol` VARCHAR(45) NULL,
  `Ustanova_oznaka` INT NOT NULL,
  PRIMARY KEY (`oznaka`, `Ustanova_oznaka`),
  INDEX `fk_StudentskiProgram_Ustanova1_idx` (`Ustanova_oznaka` ASC),
  CONSTRAINT `fk_StudentskiProgram_Ustanova1`
    FOREIGN KEY (`Ustanova_oznaka`)
    REFERENCES `mydb`.`Ustanova` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TokStudija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TokStudija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TokStudija` (
  `id` INT NOT NULL,
  `skolskaGodina` INT NULL,
  `godinaStudija` INT NULL,
  `blok` INT NULL,
  `redniBrojUpisa` INT NULL,
  `datumUpisa` DATE NULL,
  `datumOvere` DATE NULL,
  `espbPocetni` INT NULL,
  `espbKrajnji` VARCHAR(45) NULL,
  `Student_brojIndeksa` VARCHAR(45) NOT NULL,
  `Ustanova_oznaka` INT NOT NULL,
  `StudentskiProgram_oznaka` VARCHAR(45) NOT NULL,
  `StudentskiProgram_Ustanova_oznaka` INT NOT NULL,
  PRIMARY KEY (`id`, `Student_brojIndeksa`, `Ustanova_oznaka`, `StudentskiProgram_oznaka`, `StudentskiProgram_Ustanova_oznaka`),
  INDEX `fk_TokStudija_Student1_idx` (`Student_brojIndeksa` ASC),
  INDEX `fk_TokStudija_Ustanova1_idx` (`Ustanova_oznaka` ASC),
  INDEX `fk_TokStudija_StudentskiProgram1_idx` (`StudentskiProgram_oznaka` ASC, `StudentskiProgram_Ustanova_oznaka` ASC),
  CONSTRAINT `fk_TokStudija_Student1`
    FOREIGN KEY (`Student_brojIndeksa`)
    REFERENCES `mydb`.`Student` (`brojIndeksa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TokStudija_Ustanova1`
    FOREIGN KEY (`Ustanova_oznaka`)
    REFERENCES `mydb`.`Ustanova` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TokStudija_StudentskiProgram1`
    FOREIGN KEY (`StudentskiProgram_oznaka` , `StudentskiProgram_Ustanova_oznaka`)
    REFERENCES `mydb`.`StudentskiProgram` (`oznaka` , `Ustanova_oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanStudijskeGrupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlanStudijskeGrupe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PlanStudijskeGrupe` (
  `id` INT NOT NULL,
  `oznakaPrograma` VARCHAR(45) NULL,
  `blok` INT NULL,
  `pozicija` INT NULL,
  `StudentskiProgram_oznaka` VARCHAR(45) NOT NULL,
  `StudentskiProgram_Ustanova_oznaka` INT NOT NULL,
  `NastavniPredmet_oznaka` VARCHAR(45) NOT NULL,
  `NastavniPredmet_Ustanova_oznaka` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PlanStudijskeGrupe_StudentskiProgram1_idx` (`StudentskiProgram_oznaka` ASC),
  INDEX `fk_PlanStudijskeGrupe_NastavniPredmet1_idx` (`NastavniPredmet_oznaka` ASC),
  CONSTRAINT `fk_PlanStudijskeGrupe_StudentskiProgram1`
    FOREIGN KEY (`StudentskiProgram_oznaka`)
    REFERENCES `mydb`.`StudentskiProgram` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanStudijskeGrupe_NastavniPredmet1`
    FOREIGN KEY (`NastavniPredmet_oznaka`)
    REFERENCES `mydb`.`NastavniPredmet` (`oznaka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
